const ExcelJS = require('exceljs');

const NAVY = 'FF134178';
const WHITE = 'FFFFFFFF';
const HEADER_FILL = 'FFE5E7EB';

const SHEET_IDS = [
  'headline',
  'response_matrix',
  'volume',
  'peak',
  'types',
  'barangays',
  'type_barangay',
  'channels',
  'exceptions',
  'funnel',
  'utilization',
  'outcomes',
  'department',
  'incidents',
];

const INCIDENT_COLUMNS = [
  'report_id',
  'incident_type',
  'severity_level',
  'status',
  'barangay',
  'department_codes',
  'created_at',
  'resolved_at',
  'closed_at',
  'is_duplicate',
  'is_archived',
];

function cellValue(value) {
  if (value == null || value === '') return '';
  if (typeof value === 'number') return Number.isFinite(value) ? value : '';
  if (typeof value === 'boolean') return value;
  if (value instanceof Date) return value.toISOString();
  const s = String(value);
  return /^[=+\-@]/.test(s) ? `'${s}` : s;
}

function colLetter(index) {
  let n = index;
  let s = '';
  while (n > 0) {
    const rem = (n - 1) % 26;
    s = String.fromCharCode(65 + rem) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

function chrome(ws, title, meta, colCount) {
  const last = Math.max(colCount, 3);
  ws.mergeCells(1, 1, 1, last);
  const titleCell = ws.getCell(1, 1);
  titleCell.value = `RescueLink Insights · ${title}`;
  titleCell.font = { bold: true, color: { argb: WHITE }, size: 14, name: 'Calibri' };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
  titleCell.alignment = { vertical: 'middle' };
  ws.getRow(1).height = 22;
  ws.getCell(2, 1).value = `Department: ${meta.departmentName}`;
  ws.getCell(2, 2).value = `Range: ${meta.from} – ${meta.to}`;
  ws.getCell(3, 1).value = `Timezone: ${meta.timezone}`;
  ws.getCell(3, 2).value = `Generated at: ${meta.generatedAt}`;
  ws.getCell(3, 3).value = `Generated by: ${meta.generatedBy}`;
}

function writeHeaderRow(ws, rowNumber, headers) {
  const row = ws.getRow(rowNumber);
  headers.forEach((header, i) => {
    const cell = row.getCell(i + 1);
    cell.value = header;
    cell.font = { bold: true };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } };
  });
}

function addDataBar(ws, colIndex, startRow, endRow, max) {
  if (endRow < startRow) return;
  const letter = colLetter(colIndex);
  ws.addConditionalFormatting({
    ref: `${letter}${startRow}:${letter}${endRow}`,
    rules: [{
      type: 'dataBar',
      cfvo: [
        { type: 'num', value: 0 },
        { type: 'num', value: max > 0 ? max : 1 },
      ],
      color: { argb: NAVY },
      showValue: true,
      gradient: true,
    }],
  });
}

function writeTable(ws, startRow, headers, rows, barColIndexes) {
  writeHeaderRow(ws, startRow, headers);
  let maxByCol = {};
  rows.forEach((row, r) => {
    row.forEach((value, c) => {
      ws.getCell(startRow + 1 + r, c + 1).value = cellValue(value);
      if (typeof value === 'number' && Number.isFinite(value)) {
        maxByCol[c] = Math.max(maxByCol[c] || 0, value);
      }
    });
  });
  const dataStart = startRow + 1;
  const dataEnd = startRow + rows.length;
  (barColIndexes || []).forEach((colIndex) => {
    addDataBar(ws, colIndex, dataStart, dataEnd, maxByCol[colIndex - 1] || 0);
  });
  headers.forEach((_, i) => {
    ws.getColumn(i + 1).width = Math.max(14, String(headers[i]).length + 2);
  });
  return dataEnd + 2;
}

function addLabeledTable(ws, row, label, headers, rows, barColIndexes) {
  ws.getCell(row, 1).value = label;
  ws.getCell(row, 1).font = { bold: true };
  return writeTable(ws, row + 1, headers, rows, barColIndexes);
}

function emptySheet(wb, title, meta) {
  const ws = wb.addWorksheet(title.slice(0, 31));
  chrome(ws, title, meta, 3);
  ws.getCell(5, 1).value = 'No data in this range.';
}

function hasRows(rows) {
  return Array.isArray(rows) && rows.length > 0;
}

function clockP50(clock) {
  if (!clock || !clock.n) return '';
  return clock.p50_seconds == null ? '' : Number(clock.p50_seconds);
}

function clockP90(clock) {
  if (!clock || !clock.n) return '';
  return clock.p90_seconds == null ? '' : Number(clock.p90_seconds);
}

function clockP95(clock) {
  if (!clock || !clock.n) return '';
  return clock.p95_seconds == null ? '' : Number(clock.p95_seconds);
}

function buildHeadline(wb, overview, meta) {
  const kpis = overview.kpis || {};
  const clocks = overview.clocks || {};
  const ws = wb.addWorksheet('Headline');
  chrome(ws, 'Headline', meta, 4);
  let row = 5;
  row = addLabeledTable(ws, row, 'Counts', ['Metric', 'Value'], [
    ['Total incidents', Number(kpis.incidents) || 0],
    ['Critical', Number(kpis.critical) || 0],
    ['Open', Number(kpis.open) || 0],
    ['Closed', Number(kpis.closed) || 0],
    ['Unserved', Number(kpis.unserved) || 0],
    ['Overdue', Number(kpis.overdue) || 0],
  ], [2]);
  row = addLabeledTable(ws, row, 'Rates (%)', ['Metric', 'Percent'], [
    ['Duplicate rate', Number(kpis.duplicate_rate) || 0],
    ['Unserved', Number(kpis.unserved_pct) || 0],
    ['Overdue', Number(kpis.overdue_pct) || 0],
    ['Dispatch SLA', Number(kpis.dispatch_sla) || 0],
    ['Arrival SLA', Number(kpis.arrival_sla) || 0],
  ], [2]);
  writeTable(ws, row, ['Clock', 'p50_seconds', 'n'], [
    ['First action', clockP50(clocks.first_action), Number(clocks.first_action?.n) || 0],
    ['Dispatch', clockP50(clocks.dispatch), Number(clocks.dispatch?.n) || 0],
    ['Arrival', clockP50(clocks.arrival), Number(clocks.arrival?.n) || 0],
    ['Resolution', clockP50(clocks.resolve), Number(clocks.resolve?.n) || 0],
  ], []);
}

function buildResponseMatrix(wb, overview, meta) {
  const clocks = overview.clocks || {};
  const lookup = new Map((overview.breakdowns?.severity_clocks || []).map((row) => [String(row.key || '').toLowerCase(), row]));
  const metrics = [
    ['first_action', 'First action'],
    ['dispatch', 'Dispatch'],
    ['arrival', 'Arrival'],
    ['resolve', 'Resolution'],
  ];
  const rows = metrics.map(([key, label]) => {
    const overall = clocks[key];
    const critical = lookup.get('critical')?.[key];
    const high = lookup.get('high')?.[key];
    const medium = lookup.get('medium')?.[key];
    const low = lookup.get('low')?.[key];
    return [
      label,
      clockP50(overall),
      clockP90(overall),
      clockP95(overall),
      Number(overall?.n) || 0,
      clockP50(critical),
      clockP50(high),
      clockP50(medium),
      clockP50(low),
    ];
  });
  const ws = wb.addWorksheet('Response matrix');
  chrome(ws, 'Response matrix', meta, 9);
  writeTable(ws, 5, [
    'Clock', 'Overall p50', 'Overall p90', 'Overall p95', 'n',
    'Critical p50', 'High p50', 'Medium p50', 'Low p50',
  ], rows, [2, 3, 4, 6, 7, 8, 9]);
}

function buildVolume(wb, overview, meta) {
  const rows = (overview.timeseries || []).map((row) => [
    cellValue(row.bucket),
    Number(row.current) || 0,
    Number(row.previous) || 0,
  ]);
  if (!rows.length) return emptySheet(wb, 'Incident volume', meta);
  const ws = wb.addWorksheet('Incident volume');
  chrome(ws, 'Incident volume', meta, 3);
  writeTable(ws, 5, ['Period', 'This period', 'Previous period'], rows, [2]);
}

function buildPeak(wb, overview, meta) {
  const peak = overview.peak || {};
  const concurrent = overview.concurrent || {};
  const ws = wb.addWorksheet('Peak demand');
  chrome(ws, 'Peak demand', meta, 2);
  writeHeaderRow(ws, 5, ['Metric', 'Value']);
  const labels = [
    ['Peak day', peak.busiest_weekday || ''],
    ['Peak hour', peak.peak_hour_band || ''],
    ['Peak incident volume', Number(peak.peak_volume) || 0],
    ['Max concurrent', Number(peak.max_concurrent ?? concurrent.max) || 0],
    ['Avg concurrent', Number(peak.avg_concurrent ?? concurrent.avg) || 0],
  ];
  labels.forEach((row, i) => {
    ws.getCell(6 + i, 1).value = row[0];
    ws.getCell(6 + i, 2).value = cellValue(row[1]);
  });
  addDataBar(ws, 2, 8, 8, Number(peak.peak_volume) || 1);
}

function buildKeyCountPct(wb, title, rows, labelHeader, meta) {
  if (!hasRows(rows)) return emptySheet(wb, title, meta);
  const ws = wb.addWorksheet(title.slice(0, 31));
  chrome(ws, title, meta, 3);
  writeTable(ws, 5, [labelHeader, 'Count', 'Percent'], rows.map((row) => [
    row.label || row.key,
    Number(row.count) || 0,
    Number(row.pct) || 0,
  ]), [2]);
}

function buildBarangays(wb, overview, meta) {
  const rows = overview.demand?.barangays || [];
  if (!rows.length) return emptySheet(wb, 'Barangays', meta);
  const ws = wb.addWorksheet('Barangays');
  chrome(ws, 'Barangays', meta, 4);
  writeTable(ws, 5, ['Barangay', 'Count', 'Percent', 'Critical'], rows.map((row) => [
    row.key,
    Number(row.count) || 0,
    Number(row.pct) || 0,
    Number(row.critical_count) || 0,
  ]), [2]);
}

function buildTypeBarangay(wb, overview, meta) {
  const rows = overview.demand?.type_barangay || [];
  if (!rows.length) return emptySheet(wb, 'Type x barangay', meta);
  const ws = wb.addWorksheet('Type x barangay');
  chrome(ws, 'Type × barangay', meta, 3);
  writeTable(ws, 5, ['Incident type', 'Barangay', 'Count'], rows.map((row) => [
    row.incident_type,
    row.barangay,
    Number(row.count) || 0,
  ]), [3]);
}

function buildExceptions(wb, overview, meta) {
  const ex = overview.exceptions || {};
  const rows = [
    ['Reassignment', Number(ex.reassignment) || 0],
    ['Auto-assign mismatch', Number(ex.auto_assign_mismatch) || 0],
    ['Backup requested', Number(ex.backup_requested) || 0],
    ['Escalation declined', Number(ex.escalation_declined) || 0],
  ].filter((row) => row[1] > 0);
  if (!rows.length) return emptySheet(wb, 'Dispatch exceptions', meta);
  const ws = wb.addWorksheet('Dispatch exceptions');
  chrome(ws, 'Dispatch exceptions', meta, 2);
  writeTable(ws, 5, ['Type', 'Count'], rows, [2]);
}

function buildFunnel(wb, overview, meta) {
  const funnel = overview.escalation_funnel || {};
  const rows = [
    ['Escalated', Number(funnel.escalated) || 0, funnel.escalated ? 100 : 0],
    ['Accepted', Number(funnel.accepted) || 0, Number(funnel.accepted_pct) || 0],
    ['Dispatched', Number(funnel.dispatched) || 0, Number(funnel.dispatched_pct) || 0],
    ['Arrived', Number(funnel.arrived) || 0, Number(funnel.arrived_pct) || 0],
  ];
  if (!rows[0][1]) return emptySheet(wb, 'Escalation funnel', meta);
  const ws = wb.addWorksheet('Escalation funnel');
  chrome(ws, 'Escalation funnel', meta, 3);
  writeTable(ws, 5, ['Step', 'Count', 'Percent of escalated'], rows, [2]);
}

function buildUtilization(wb, overview, meta) {
  const util = overview.utilization || {};
  const units = overview.units || {};
  const rows = [
    ['Units used', Number(util.units_used) || 0],
    ['Dispatches', Number(util.dispatch_count) || 0],
  ];
  if (units.available_units != null) rows.push(['Available units', Number(units.available_units) || 0]);
  if (units.total_units != null) rows.push(['Total units', Number(units.total_units) || 0]);
  if (units.personnel_count != null) rows.push(['Personnel', Number(units.personnel_count) || 0]);
  const ws = wb.addWorksheet('Resource utilization');
  chrome(ws, 'Resource utilization', meta, 2);
  writeTable(ws, 5, ['Metric', 'Count'], rows, [2]);
}

function buildDepartment(wb, overview, meta) {
  const counts = overview.breakdowns?.department || [];
  const clocks = overview.breakdowns?.department_clocks || [];
  if (!counts.length && !clocks.length) return emptySheet(wb, 'By department', meta);
  const ws = wb.addWorksheet('By department');
  chrome(ws, 'By department', meta, 6);
  let row = 5;
  if (counts.length) {
    row = addLabeledTable(ws, row, 'Incident count', ['Department', 'Count'], counts.map((r) => [
      r.key,
      Number(r.count) || 0,
    ]), [2]);
  }
  if (clocks.length) {
    writeTable(ws, row, ['Department', 'Dispatch p50', 'Arrival p50', 'n', 'Primary', 'Supporting'], clocks.map((r) => [
      r.key,
      r.dispatch_p50_seconds == null ? '' : Number(r.dispatch_p50_seconds),
      r.arrival_p50_seconds == null ? '' : Number(r.arrival_p50_seconds),
      Number(r.n) || 0,
      Number(r.primary_n) || 0,
      Number(r.supporting_n) || 0,
    ]), []);
  }
}

function buildIncidents(wb, incidents, meta) {
  const ws = wb.addWorksheet('Incidents');
  chrome(ws, 'Incidents', meta, INCIDENT_COLUMNS.length);
  writeTable(ws, 5, INCIDENT_COLUMNS, (incidents || []).map((row) => INCIDENT_COLUMNS.map((key) => {
    const value = row[key];
    if (value instanceof Date) return value.toISOString();
    if (value && typeof value === 'object' && typeof value.toISOString === 'function') return value.toISOString();
    return value;
  })), []);
}

const BUILDERS = {
  headline: (wb, ctx) => buildHeadline(wb, ctx.overview, ctx.meta),
  response_matrix: (wb, ctx) => buildResponseMatrix(wb, ctx.overview, ctx.meta),
  volume: (wb, ctx) => buildVolume(wb, ctx.overview, ctx.meta),
  peak: (wb, ctx) => buildPeak(wb, ctx.overview, ctx.meta),
  types: (wb, ctx) => buildKeyCountPct(wb, 'Incident types', ctx.overview.demand?.types, 'Type', ctx.meta),
  barangays: (wb, ctx) => buildBarangays(wb, ctx.overview, ctx.meta),
  type_barangay: (wb, ctx) => buildTypeBarangay(wb, ctx.overview, ctx.meta),
  channels: (wb, ctx) => buildKeyCountPct(wb, 'Reporting channels', ctx.overview.demand?.channels, 'Channel', ctx.meta),
  exceptions: (wb, ctx) => buildExceptions(wb, ctx.overview, ctx.meta),
  funnel: (wb, ctx) => buildFunnel(wb, ctx.overview, ctx.meta),
  utilization: (wb, ctx) => buildUtilization(wb, ctx.overview, ctx.meta),
  outcomes: (wb, ctx) => buildKeyCountPct(wb, 'Resolution outcomes', ctx.overview.outcomes, 'Outcome', ctx.meta),
  department: (wb, ctx) => buildDepartment(wb, ctx.overview, ctx.meta),
  incidents: (wb, ctx) => buildIncidents(wb, ctx.incidents, ctx.meta),
};

function shouldBuild(id, overview) {
  if (id === 'department') {
    return Boolean((overview.breakdowns?.department || []).length || (overview.breakdowns?.department_clocks || []).length);
  }
  return true;
}

async function buildInsightsWorkbook({ overview, incidents = [], filters = {}, generatedBy = 'unknown', sheet = null }) {
  const meta = {
    departmentName: overview.department?.name || filters.department_name || (filters.volunteer_scope ? 'Volunteers' : 'All departments'),
    from: filters.from || '',
    to: filters.to || '',
    timezone: overview.timezone || 'Asia/Manila',
    generatedAt: overview.generated_at || new Date().toISOString(),
    generatedBy,
  };
  const wb = new ExcelJS.Workbook();
  wb.creator = 'RescueLink';
  const ids = sheet ? [sheet] : SHEET_IDS.filter((id) => shouldBuild(id, overview));
  for (const id of ids) {
    BUILDERS[id](wb, { overview, incidents, meta });
  }
  if (!wb.worksheets.length) emptySheet(wb, 'Insights', meta);
  return wb.xlsx.writeBuffer();
}

module.exports = {
  SHEET_IDS,
  INCIDENT_COLUMNS,
  buildInsightsWorkbook,
};
