const ExcelJS = require('exceljs');

const NAVY = 'FF134178';
const WHITE = 'FFFFFFFF';
const HEADER_FILL = 'FFE5E7EB';

const ACTION_LABELS = {
  dispatcher_login: 'Login',
  dispatcher_signup: 'Signup',
  dispatcher_logout: 'Logout',
  password_change: 'Password change',
  password_reset: 'Password reset',
  dispatch_create: 'Dispatch created',
  dispatch_update: 'Dispatch updated',
  dispatch_delete: 'Dispatch deleted',
  incident_blockchain_finalize: 'Incident finalized',
  incident_verify: 'Incident verified (legacy)',
};

function cellValue(value) {
  if (value == null || value === '') return '';
  if (typeof value === 'number') return Number.isFinite(value) ? value : '';
  if (typeof value === 'boolean') return value;
  if (value instanceof Date) return value.toISOString();
  const s = String(value);
  return /^[=+\-@]/.test(s) ? `'${s}` : s;
}

function chrome(ws, title, meta, colCount) {
  const last = Math.max(colCount, 3);
  ws.mergeCells(1, 1, 1, last);
  const titleCell = ws.getCell(1, 1);
  titleCell.value = `RescueLink · ${title}`;
  titleCell.font = { bold: true, color: { argb: WHITE }, size: 14, name: 'Calibri' };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
  titleCell.alignment = { vertical: 'middle' };
  ws.getRow(1).height = 22;
  ws.getCell(2, 1).value = meta.filterLine || 'Filters: (none)';
  ws.getCell(3, 1).value = `Generated at: ${meta.generatedAt}`;
  ws.getCell(3, 2).value = `Generated by: ${meta.generatedBy}`;
}

function writeHeaderRow(ws, rowNumber, headers) {
  const row = ws.getRow(rowNumber);
  headers.forEach((header, i) => {
    const cell = row.getCell(i + 1);
    cell.value = header;
    cell.font = { bold: true };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } };
  });
}

function actionLabel(action) {
  if (!action) return '';
  return ACTION_LABELS[action] || String(action).replace(/_/g, ' ');
}

function userLabel(log) {
  if (log.user_email) return log.user_email;
  const name = [log.user_first_name, log.user_last_name].filter(Boolean).join(' ');
  if (name) return name;
  return log.user_id != null ? `User #${log.user_id}` : '';
}

function detailFields(details) {
  if (details == null) return { block: '', tx: '', text: '' };
  let obj = details;
  if (typeof details === 'string') {
    try {
      obj = JSON.parse(details);
    } catch {
      return { block: '', tx: '', text: details };
    }
  }
  if (typeof obj !== 'object') return { block: '', tx: '', text: String(details) };
  const block = obj.block_number != null ? String(obj.block_number) : '';
  const tx = obj.tx_hash != null ? String(obj.tx_hash) : '';
  const entries = Object.entries(obj).filter(([, v]) => v != null && v !== '');
  const text = entries.length ? entries.map(([k, v]) => `${k}: ${v}`).join(', ') : '';
  return { block, tx, text };
}

function buildAuditLogWorkbook(logs, meta) {
  const wb = new ExcelJS.Workbook();
  const headers = ['Timestamp', 'User', 'Action', 'Resource', 'Resource ID', 'Block', 'Tx Hash', 'Details'];
  const ws = wb.addWorksheet('Audit log');
  chrome(ws, 'Dispatcher Audit Log', meta, headers.length);
  writeHeaderRow(ws, 5, headers);
  const startRow = 6;
  (logs || []).forEach((log, index) => {
    const rowNum = startRow + index;
    const { block, tx, text } = detailFields(log.details);
    const values = [
      log.created_at ? new Date(log.created_at).toISOString() : '',
      userLabel(log),
      actionLabel(log.action),
      log.resource_type || '',
      log.resource_id != null ? log.resource_id : '',
      block,
      tx,
      text,
    ];
    values.forEach((value, col) => {
      ws.getCell(rowNum, col + 1).value = cellValue(value);
    });
  });
  headers.forEach((header, i) => {
    ws.getColumn(i + 1).width = Math.max(14, String(header).length + 2);
  });
  ws.getColumn(8).width = 48;
  return wb.xlsx.writeBuffer();
}

module.exports = {
  buildAuditLogWorkbook,
  actionLabel,
};
