const ExcelJS = require('exceljs');

const NAVY = 'FF134178';
const WHITE = 'FFFFFFFF';
const HEADER_FILL = 'FFE5E7EB';

const ACTION_LABELS = {
  dispatcher_login: 'Dispatcher login',
  dispatcher_signup: 'Dispatcher signup',
  dispatcher_logout: 'Logout',
  password_change: 'Password changed',
  password_reset: 'Password reset',
  user_register: 'Account registered',
  user_login: 'Citizen login',
  user_logout: 'Citizen logout',
  user_profile_update: 'Profile updated',
  user_avatar_update: 'Profile photo updated',
  user_avatar_delete: 'Profile photo removed',
  dispatch_create: 'Dispatch created',
  dispatch_create_v2: 'Dispatch created',
  dispatch_create_department_only: 'Department notified',
  dispatch_create_auto_team: 'Auto team dispatch',
  dispatch_update: 'Dispatch updated',
  dispatch_delete: 'Dispatch deleted',
  dispatch_undo_department_notification: 'Department notification undone',
  dispatch_confirm_suggestion: 'Team suggestion confirmed',
  dispatch_reassign_team: 'Team reassigned',
  incident_create: 'Incident reported',
  incident_blockchain_finalize: 'Incident finalized',
  incident_verify: 'Incident verified (legacy)',
  incident_reporter_confirm_resolution: 'Resolution confirmed',
  incident_reporter_cancel: 'Report cancelled',
  incident_reporter_update_details: 'Report details updated',
  incident_status_update: 'Incident status updated',
  add_coordination_note: 'Coordination note added',
  department_create: 'Created department',
  department_update: 'Updated department',
  department_delete: 'Deleted department',
  department_unit_create: 'Added unit',
  department_unit_update: 'Updated unit',
  department_unit_delete: 'Removed unit',
  department_unit_assign: 'Assigned unit to incident',
  department_personnel_create: 'Added roster person',
  department_personnel_update: 'Updated roster person',
  department_personnel_delete: 'Removed roster person',
  responder_create: 'Created responder',
  responder_update: 'Updated responder',
  responder_status_update: 'Responder status updated',
  responder_delete: 'Deleted responder',
  responder_team_create: 'Created team',
  responder_team_update: 'Updated team',
  responder_team_status_update: 'Team status updated',
  responder_team_delete: 'Deleted team',
  responder_team_member_add: 'Added team member',
  responder_team_member_remove: 'Removed team member',
  responder_application_submit: 'Volunteer application submitted',
  responder_application_approved: 'Application approved',
  responder_application_rejected: 'Application rejected',
  responder_application_revoked: 'Responder role revoked',
  escalation_request: 'Assistance requested',
  escalation_accepted: 'Assistance accepted',
  escalation_declined: 'Assistance declined',
  escalation_resolved: 'Assistance resolved',
  escalation_cancelled: 'Assistance cancelled',
};

const RESOURCE_LABELS = {
  auth: 'Auth',
  dispatch: 'Dispatch',
  incident: 'Incident',
  department: 'Department',
  department_unit: 'Unit',
  department_personnel: 'Roster',
  responder: 'Responder',
  team: 'Team',
  escalation: 'Escalation',
  responder_application: 'Application',
  analytics: 'Analytics',
  user: 'User',
};

function cellValue(value) {
  if (value == null || value === '') return '';
  if (typeof value === 'number') return Number.isFinite(value) ? value : '';
  if (typeof value === 'boolean') return value;
  if (value instanceof Date) return value.toISOString();
  const s = String(value);
  return /^[=+\-@]/.test(s) ? `'${s}` : s;
}

function chrome(ws, title, meta, colCount) {
  const last = Math.max(colCount, 3);
  ws.mergeCells(1, 1, 1, last);
  const titleCell = ws.getCell(1, 1);
  titleCell.value = `RescueLink · ${title}`;
  titleCell.font = { bold: true, color: { argb: WHITE }, size: 14, name: 'Calibri' };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
  titleCell.alignment = { vertical: 'middle' };
  ws.getRow(1).height = 22;
  ws.getCell(2, 1).value = meta.filterLine || 'Filters: (none)';
  ws.getCell(3, 1).value = `Generated at: ${meta.generatedAt}`;
  ws.getCell(3, 2).value = `Generated by: ${meta.generatedBy}`;
}

function writeHeaderRow(ws, rowNumber, headers) {
  const row = ws.getRow(rowNumber);
  headers.forEach((header, i) => {
    const cell = row.getCell(i + 1);
    cell.value = header;
    cell.font = { bold: true };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } };
  });
}

function actionLabel(action) {
  if (!action) return '';
  return ACTION_LABELS[action] || String(action).replace(/_/g, ' ');
}

function resourceLabel(resourceType) {
  if (!resourceType) return '';
  return RESOURCE_LABELS[resourceType] || String(resourceType).replace(/_/g, ' ');
}

function userLabel(log) {
  if (log.user_email) return log.user_email;
  const name = [log.user_first_name, log.user_last_name].filter(Boolean).join(' ');
  if (name) return name;
  return log.user_id != null ? `User #${log.user_id}` : '';
}

function detailFields(details) {
  if (details == null) return { block: '', tx: '', text: '' };
  let obj = details;
  if (typeof details === 'string') {
    try {
      obj = JSON.parse(details);
    } catch {
      return { block: '', tx: '', text: details };
    }
  }
  if (typeof obj !== 'object') return { block: '', tx: '', text: String(details) };
  const block = obj.block_number != null ? String(obj.block_number) : '';
  const tx = obj.tx_hash != null ? String(obj.tx_hash) : '';
  const entries = Object.entries(obj).filter(([, v]) => v != null && v !== '');
  const text = entries.length ? entries.map(([k, v]) => `${k}: ${v}`).join(', ') : '';
  return { block, tx, text };
}

function buildAuditLogWorkbook(logs, meta) {
  const wb = new ExcelJS.Workbook();
  const headers = [
    'Timestamp',
    'User',
    'Action',
    'Action code',
    'Area',
    'Resource type',
    'Resource ID',
    'Block',
    'Tx Hash',
    'Details',
  ];
  const ws = wb.addWorksheet('Audit log');
  chrome(ws, 'Dispatcher Audit Log', meta, headers.length);
  writeHeaderRow(ws, 5, headers);
  const startRow = 6;
  const maxLens = headers.map((h) => String(h).length);
  (logs || []).forEach((log, index) => {
    const rowNum = startRow + index;
    const { block, tx, text } = detailFields(log.details);
    const values = [
      log.created_at ? new Date(log.created_at).toISOString() : '',
      userLabel(log),
      actionLabel(log.action),
      log.action || '',
      resourceLabel(log.resource_type),
      log.resource_type || '',
      log.resource_id != null ? log.resource_id : '',
      block,
      tx,
      text,
    ];
    values.forEach((value, col) => {
      const cell = cellValue(value);
      ws.getCell(rowNum, col + 1).value = cell;
      const len = String(cell ?? '').length;
      if (len > maxLens[col]) maxLens[col] = len;
    });
  });
  // Excel width ≈ character count; pad and clamp so short headers stay readable and long details don't explode.
  const MIN_W = 10;
  const MAX_W = 60;
  maxLens.forEach((len, i) => {
    ws.getColumn(i + 1).width = Math.min(MAX_W, Math.max(MIN_W, len + 2));
  });
  return wb.xlsx.writeBuffer();
}

/** Exported for regression: same clamp used when sizing columns from content. */
function columnWidthForContent(charLen, { min = 10, max = 60, pad = 2 } = {}) {
  return Math.min(max, Math.max(min, Number(charLen) + pad));
}

module.exports = {
  buildAuditLogWorkbook,
  actionLabel,
  resourceLabel,
  columnWidthForContent,
  ACTION_LABELS,
  RESOURCE_LABELS,
};
