# Reads pubspec.yaml version (name+number), optional FLUTTER_BUILD_NAME / FLUTTER_BUILD_NUMBER overrides.
# Writes lib/config/app_version.generated.dart and prints "name buildNumber" for callers.
param(
    [string]$MobileRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$pubspecPath = Join-Path $MobileRoot "pubspec.yaml"
if (-not (Test-Path $pubspecPath)) {
    Write-Error "pubspec.yaml not found at $pubspecPath"
    exit 1
}

$match = Select-String -Path $pubspecPath -Pattern '^\s*version:\s*(\S+)\s*$' | Select-Object -First 1
if (-not $match) {
    Write-Error "No version: line in pubspec.yaml"
    exit 1
}

$full = $match.Matches.Groups[1].Value
$split = $full -split '\+', 2
$name = $split[0]
$number = if ($split.Length -gt 1 -and $split[1]) { $split[1] } else { '1' }

if ($env:FLUTTER_BUILD_NAME) { $name = $env:FLUTTER_BUILD_NAME.Trim() }
if ($env:FLUTTER_BUILD_NUMBER) { $number = $env:FLUTTER_BUILD_NUMBER.Trim() }

$nameEscaped = $name -replace "'", "\\'"
$numberEscaped = $number -replace "'", "\\'"

$outDir = Join-Path $MobileRoot "lib\config"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$outFile = Join-Path $outDir "app_version.generated.dart"
@(
    "// Generated by scripts/sync_app_version.ps1 - do not edit by hand.",
    "const String kAppVersionName = '$nameEscaped';",
    "const String kAppBuildNumber = '$numberEscaped';",
    ""
) | Set-Content -Path $outFile -Encoding utf8

Write-Output "$name $number"
exit 0
